comparisons:
  - name: method_scores
    feature_requests:
      - feature_set: method_scores

  - name: method_scores_plus_target_context
    feature_requests:
      - feature_set: method_scores
      - feature_set: target_context
        base_feature_set: method_scores

  - name: method_scores_plus_glide_uncertainty_plus_target_context
    feature_requests:
      - feature_set: method_scores
      - feature_set: glide_uncertainty
      - feature_set: target_context
        base_feature_set: method_scores

  - name: method_scores_plus_method_ranks_plus_rank_summary_plus_target_context
    feature_requests:
      - feature_set: method_scores
      - feature_set: method_ranks
      - feature_set: method_rank_summary
      - feature_set: target_context
        base_feature_set: method_scores

  - name: chemical_descriptors
    feature_requests:
      - feature_set: chemical_descriptors

  - name: method_scores_plus_chemical_descriptors_plus_target_context
    feature_requests:
      - feature_set: method_scores
      - feature_set: chemical_descriptors
      - feature_set: target_context
        base_feature_set: method_scores

  - name: method_scores_plus_method_ranks_plus_rank_summary_plus_glide_uncertainty_plus_chemical_descriptors_plus_target_context
    feature_requests:
      - feature_set: method_scores
      - feature_set: method_ranks
      - feature_set: method_rank_summary
      - feature_set: glide_uncertainty
      - feature_set: chemical_descriptors
      - feature_set: target_context
        base_feature_set: method_scores
