comparisons:
  - name: 6predictor_pr
    feature_requests:
      - feature_set: 6predictor_pr
        source: shared

  - name: 6predictor_pr_plus_derived
    feature_requests:
      - feature_set: 6predictor_pr
        source: shared
      - feature_set: 6predictor_pr_derived
        source: shared

  - name: 6predictor_pr_derived_only
    feature_requests:
      - feature_set: 6predictor_pr_derived
        source: shared

  - name: chemdescriptors_only
    feature_requests:
      - feature_set: chemdescriptors
        source: shared

  - name: 6predictor_pr_plus_chemdescriptors
    feature_requests:
      - feature_set: 6predictor_pr
        source: shared
      - feature_set: chemdescriptors
        source: shared

  - name: 6predictor_pr_plus_derived_plus_chemdescriptors
    feature_requests:
      - feature_set: 6predictor_pr
        source: shared
      - feature_set: 6predictor_pr_derived
        source: shared
      - feature_set: chemdescriptors
        source: shared
