comparisons:
  - name: method_scores
    feature_requests:
      - feature_set: method_scores

  - name: method_scores_plus_glide_uncertainty
    feature_requests:
      - feature_set: method_scores
      - feature_set: glide_uncertainty

  - name: method_ranks
    feature_requests:
      - feature_set: method_ranks

  - name: method_scores_plus_method_ranks
    feature_requests:
      - feature_set: method_scores
      - feature_set: method_ranks

  - name: method_scores_plus_method_ranks_plus_rank_summary
    feature_requests:
      - feature_set: method_scores
      - feature_set: method_ranks
      - feature_set: method_rank_summary

  - name: chemical_descriptors
    feature_requests:
      - feature_set: chemical_descriptors

  - name: method_scores_plus_chemical_descriptors
    feature_requests:
      - feature_set: method_scores
      - feature_set: chemical_descriptors

  - name: method_scores_plus_method_ranks_plus_rank_summary_plus_glide_uncertainty_plus_chemical_descriptors
    feature_requests:
      - feature_set: method_scores
      - feature_set: method_ranks
      - feature_set: method_rank_summary
      - feature_set: glide_uncertainty
      - feature_set: chemical_descriptors
